---
title: "MIMIC-Dep-test"
author: "Jianhui Gao"
date: "2024-12-11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```

```{r}
library(dplyr)
library(glmnet)
library(randomForest)
library(SSFairnessAudit)
library(tidyr)
library(ggplot2)
library(ggpubr)
library(pROC)
```

```{r}
dat <- readRDS("MIMIC-III/Depression model/depression_data.rds")

Y_silver <- ifelse(dat$s_v + dat$icd_cnt > 0, 1, 0)
X_structured <- dat %>%
  select(`ADMISSION_TYPE.EMERGENCY.URGENT`:GENDER.M, AGE)
X_NLP <- dat %>%
  select(starts_with("cnt")) %>%
  select_if(colSums(.) != 0) # remove all 0s

set.seed(123)
model <- randomForest::randomForest(cbind(X_structured, X_NLP) %>% as.matrix(), factor(Y_silver))

#Y_silver_hat <- predict(model, cbind(X_structured, X_NLP) %>% as.matrix(), type = "response")

Y_silver_hat <- predict(model, cbind(X_structured, X_NLP) %>% as.matrix(), type = "prob")[, 2]

labeled_ind <- !is.na(dat$y_v)
threshold <- 0.23
#sum(dat$y_v[labeled_ind] == 0 & Y_silver_hat[labeled_ind] > threshold) / sum(dat$y_v[labeled_ind] == 0)
```


# Gender 

```{r}
cat("Male in labeled dataset ", mean(dat$GENDER.M[labeled_ind]), "\n")
cat("Male in unlabeled dataset ", mean(dat$GENDER.M[-labeled_ind]), "\n")
```



## Calibration

```{r, fig.width=6, fig.height=3}
par(mfrow = c(1, 2))
p <- roc(dat$y_v[dat$GENDER.M == 0], Y_silver_hat[dat$GENDER.M == 0], plot = TRUE,  print.auc = TRUE, main = "Female")
p <- roc(dat$y_v[dat$GENDER.M == 1], Y_silver_hat[dat$GENDER.M == 1], plot = TRUE, print.auc = TRUE, main = "Male")
```

```{r, fig.width=6, fig.height=3}

compute_calibration_data <- function(predictions, outcomes) {
  data.frame(predictions, outcomes) %>%
    mutate(bin = cut(predictions, breaks = seq(0, 1, by = 0.1), include.lowest = TRUE)) %>%
    group_by(bin) %>%
    summarise(mean_prediction = mean(predictions),
              observed_frequency = mean(outcomes),
              .groups = 'drop')
}

# protected attributes
A <- dat$GENDER.M

# Compute calibration data for overall and each subgroup
calibration_overall <- compute_calibration_data(Y_silver_hat[labeled_ind], dat$y_v[labeled_ind])
calibration_0 <- compute_calibration_data(Y_silver_hat[labeled_ind][A[labeled_ind] == 0], dat$y_v[labeled_ind][A[labeled_ind] == 0])
calibration_1 <- compute_calibration_data(Y_silver_hat[labeled_ind][A[labeled_ind] == 1], dat$y_v[labeled_ind][A[labeled_ind] == 1])

p1 <- ggplot(calibration_0, aes(x = mean_prediction, y = observed_frequency)) +
  geom_point() +
  geom_line() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "black") +
  ggtitle("Female")

p2 <- ggplot(calibration_1, aes(x = mean_prediction, y = observed_frequency)) +
  geom_point() +
  geom_line() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "black") +
  ggtitle("Male")

ggarrange(p1, p2, ncol = 2)
```

## Point Estimate at Overall FPR = 10%

```{r, fig.width=8, fig.height=4}
protect_attributes <- X_structured %>%
  select(INSURANCE.Medicare.Private, INSURANCE.Self.Pay.Government,
         MARITAL_STATUS.MARRIED, MARITAL_STATUS.SEPARATED,
         MARITAL_STATUS.WIDOWED.SINGLE.DIVORCED, 
         ETHNICITY.OTHER.HISPANIC, ETHNICITY.WHITE.BLACK,
         GENDER.M, AGE)
  
add_X <- protect_attributes %>% select(-GENDER.M) %>% as.matrix()

# protected attributes
A <- dat$GENDER.M

# Supervised Estimator
sup <- Audit_Fairness(Y = dat$y_v,
                      S = Y_silver_hat,
                      A = A,
                      threshold = threshold,
                      method = "supervised")

# Semi-Supervised Estimator using glm(S)
ss <- Audit_Fairness(Y = dat$y_v,
                     S = Y_silver_hat,
                     A = A,
                     threshold = threshold,
                     method = "semi-supervised",
                     X = add_X)

### ----------------------------- Formatting ----------------------------------
sup <- sup$est %>%
  pivot_longer(
    cols = -c(Metric),
    names_to = "Group",
    values_to = "Est"
  ) %>%
  left_join(
    sup$var %>%
      pivot_longer(
        cols = -c(Metric),
        names_to = "Group",
        values_to = "Var"
      ),
    by = c("Metric", "Group")
  ) %>%
  mutate(Method = "Supervised")

ss <- ss$est %>%
  pivot_longer(
    cols = -c(Metric),
    names_to = "Group",
    values_to = "Est"
  ) %>%
  left_join(
    ss$var %>%
      pivot_longer(
        cols = -c(Metric),
        names_to = "Group",
        values_to = "Var"
      ),
    by = c("Metric", "Group")
  ) %>%
  mutate(Method = "SS")

re <- data.frame(
  Metric = sup$Metric, Group = sup$Group,
  RE = sup$Var / ss$Var, Method = "glm(S)"
)

library(ggsci)

rbind(sup, ss) %>%
  filter(!Metric %in% c("TNR", "FNR"))  %>%
  mutate(Method = factor(Method, levels = c("Supervised" ,"SS"))) %>%
  mutate(Group = factor(Group,
    levels = c("Group0", "Group1", "Delta"),
    labels = c("Female", "Male", "Delta")
  )) %>%
  ggplot(aes(x = Metric, y = Est, color = Method)) +
  geom_point(position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = Est - 1.96 * sqrt(Var), ymax = Est + 1.9 * sqrt(Var)), position = position_dodge(width = 0.9), width = 0.25) +
  facet_wrap(~Group) +
  theme_bw() +
  theme(
    legend.position = "bottom"
  ) + # Increase facet labels size
  xlab("") +
  ylab("") +
  scale_color_manual(values = pal_nejm()(3)[-1])

ggsave("MIMIC-III/Depression model/Gender_Est.png", width = 12, height = 6)
```

## RE 

```{r, fig.width=8, fig.height=4}
re %>%
  data.frame()  %>%
  filter(!Metric %in% c("TNR", "FNR"))  %>%
  mutate(Group = factor(Group,
    levels = c("Group0", "Group1", "Delta"),
    labels = c("Female", "Male", "Delta")
  )) %>%
  ggplot(aes(x = Metric, y = sqrt(RE), fill = Group)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_bw() +
  xlab("") +
  ylab("Confidence Interval Length Ratio\n Supervised : Semi-Supervised") +
  scale_fill_cosmic() + 
  geom_hline(yintercept = 1, linetype = "dashed", color = "red") +
  theme(
    legend.position = "bottom"
  ) + 
  scale_y_continuous(breaks = c(0, 0.5, 1, 1.2, 1.4))

ggsave("MIMIC-III/Depression model/Gender_RE.png", width = 8, height = 4)
  
```



\clearpage

# Race (White vs Non-White)

```{r}
dat$is_white <- ifelse(grepl("WHITE", dat$ETHNICITY), 1, 0)
cat("White in labeled dataset ", mean(dat$is_white[labeled_ind]), "\n")
cat("White in unlabeled dataset ", mean(dat$is_white[-labeled_ind]), "\n")
mean(dat$y_v[labeled_ind][dat$is_white[labeled_ind] == 1])
mean(dat$y_v[labeled_ind][dat$is_white[labeled_ind] == 0])
```

## Calibration

```{r, fig.width=6, fig.height=3}
par(mfrow = c(1, 2))
p <- p <- roc(dat$y_v[dat$is_white == 0], Y_silver_hat[dat$is_white == 0], plot = TRUE,  print.auc = TRUE, main = "Non-White")
p <- p <- roc(dat$y_v[dat$is_white == 1], Y_silver_hat[dat$is_white == 1], plot = TRUE, print.auc = TRUE, main = "White")
```

```{r, fig.width=6, fig.height=3}
# protected attributes
A <- dat$is_white

# Compute calibration data for overall and each subgroup
calibration_overall <- compute_calibration_data(Y_silver_hat[labeled_ind], dat$y_v[labeled_ind])
calibration_0 <- compute_calibration_data(Y_silver_hat[labeled_ind][A[labeled_ind] == 0], dat$y_v[labeled_ind][A[labeled_ind] == 0])
calibration_1 <- compute_calibration_data(Y_silver_hat[labeled_ind][A[labeled_ind] == 1], dat$y_v[labeled_ind][A[labeled_ind] == 1])

p1 <- ggplot(calibration_0, aes(x = mean_prediction, y = observed_frequency)) +
  geom_point() +
  geom_line() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "black") +
  ggtitle("Female")

p2 <- ggplot(calibration_1, aes(x = mean_prediction, y = observed_frequency)) +
  geom_point() +
  geom_line() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "black") +
  ggtitle("Male")

ggarrange(p1, p2, ncol = 2)
```

## Point Estimate at Overall FPR = 10%

```{r, fig.width=8, fig.height=4}
protect_attributes <- X_structured %>%
  select(INSURANCE.Medicare.Private, INSURANCE.Self.Pay.Government,
         MARITAL_STATUS.MARRIED, MARITAL_STATUS.SEPARATED,
         MARITAL_STATUS.WIDOWED.SINGLE.DIVORCED, 
         ETHNICITY.OTHER.HISPANIC, ETHNICITY.WHITE.BLACK,
         GENDER.M, AGE)
  
add_X <- protect_attributes %>% select(-ETHNICITY.OTHER.HISPANIC, -ETHNICITY.WHITE.BLACK) %>% as.matrix()

# Supervised Estimator
sup <- Audit_Fairness(Y = dat$y_v[labeled_ind],
                      S = Y_silver_hat[labeled_ind],
                      A = A[labeled_ind],
                      threshold = threshold,
                      method = "supervised")
  
# Semi-Supervised Estimator using glm(S)
ss <- Audit_Fairness(Y = dat$y_v,
                     S = Y_silver_hat,
                     A = A,
                     threshold = threshold,
                     method = "semi-supervised",
                     X = add_X)

### ----------------------------- Formatting ----------------------------------
sup <- sup$est %>%
  pivot_longer(
    cols = -c(Metric),
    names_to = "Group",
    values_to = "Est"
  ) %>%
  left_join(
    sup$var %>%
      pivot_longer(
        cols = -c(Metric),
        names_to = "Group",
        values_to = "Var"
      ),
    by = c("Metric", "Group")
  ) %>%
  mutate(Method = "Supervised")

ss <- ss$est %>%
  pivot_longer(
    cols = -c(Metric),
    names_to = "Group",
    values_to = "Est"
  ) %>%
  left_join(
    ss$var %>%
      pivot_longer(
        cols = -c(Metric),
        names_to = "Group",
        values_to = "Var"
      ),
    by = c("Metric", "Group")
  ) %>%
  mutate(Method = "SS")

re <- data.frame(
  Metric = sup$Metric, Group = sup$Group,
  RE = sup$Var / ss$Var, Method = "glm(S)"
)

library(ggsci)

rbind(sup, ss) %>%
  filter(!Metric %in% c("TNR", "FNR"))  %>%
  mutate(Method = factor(Method, levels = c("Supervised" ,"SS"))) %>%
  mutate(Group = factor(Group,
    levels = c("Group0", "Group1", "Delta"),
    labels = c("non-White", "White", "Delta")
  )) %>%
  ggplot(aes(x = Metric, y = Est, color = Method)) +
  geom_point(position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = Est - 1.96 * sqrt(Var), ymax = Est + 1.9 * sqrt(Var)), position = position_dodge(width = 0.9), width = 0.25) +
  facet_wrap(~Group) +
  theme_bw() +
  theme(
    legend.position = "bottom"
  ) + # Increase facet labels size
  xlab("") +
  ylab("") +
  scale_color_manual(values = pal_nejm()(3)[-1])
ggsave("MIMIC-III/Depression model/Race_Est.png", width = 12, height = 6)
```

## RE 

```{r, fig.width=8, fig.height=4}
re %>%
  data.frame()  %>%
  filter(!Metric %in% c("TNR", "FNR"))  %>%
  mutate(Group = factor(Group,
    levels = c("Group0", "Group1", "Delta"),
    labels = c("non-White", "White", "Delta")
  )) %>%
  ggplot(aes(x = Metric, y = sqrt(RE), fill = Group)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_bw() +
  xlab("") +
  ylab("Confidence Interval Length Ratio\n Supervised : Semi-Supervised") +
  scale_fill_cosmic() +
  geom_hline(yintercept = 1, linetype = "dashed", color = "red") +
  theme(
    legend.position = "bottom"
  ) +
  scale_y_continuous(breaks = c(0, 0.5, 1, 1.2, 1.4))

ggsave("MIMIC-III/Depression model/Race_RE.png", width = 8, height = 4)
```


\clearpage

# Marital Status (Married vs Non-Married)

```{r}
dat$is_married <- ifelse(grepl("MARRIED", dat$MARITAL_STATUS), 1, 0)
cat("Married in labeled dataset ", mean(dat$is_married[labeled_ind]), "\n")
cat("Married in unlabeled dataset ", mean(dat$is_married[-labeled_ind]), "\n")

```

## Calibration

```{r, fig.width=6, fig.height=3}
par(mfrow = c(1, 2))
p <- roc(dat$y_v[dat$is_married == 0], Y_silver_hat[dat$is_married == 0], plot = TRUE,  print.auc = TRUE, main = "Non-Married")
p <- roc(dat$y_v[dat$is_married == 1], Y_silver_hat[dat$is_married == 1], plot = TRUE, print.auc = TRUE, main = "Married")
```


```{r, fig.width=6, fig.height=3}
# protected attributes
A <- dat$is_married

# Compute calibration data for overall and each subgroup
calibration_overall <- compute_calibration_data(Y_silver_hat[labeled_ind], dat$y_v[labeled_ind])
calibration_0 <- compute_calibration_data(Y_silver_hat[labeled_ind][A[labeled_ind] == 0], dat$y_v[labeled_ind][A[labeled_ind] == 0])
calibration_1 <- compute_calibration_data(Y_silver_hat[labeled_ind][A[labeled_ind] == 1], dat$y_v[labeled_ind][A[labeled_ind] == 1])

p1 <- ggplot(calibration_0, aes(x = mean_prediction, y = observed_frequency)) +
  geom_point() +
  geom_line() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "black") +
  ggtitle("Female")

p2 <- ggplot(calibration_1, aes(x = mean_prediction, y = observed_frequency)) +
  geom_point() +
  geom_line() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "black") +
  ggtitle("Male")

ggarrange(p1, p2, ncol = 2)
```

## Point Estimate at Overall FPR = 10%

```{r, fig.width=8, fig.height=4}
protect_attributes <- X_structured %>%
  select(INSURANCE.Medicare.Private, INSURANCE.Self.Pay.Government,
         MARITAL_STATUS.MARRIED, MARITAL_STATUS.SEPARATED,
         MARITAL_STATUS.WIDOWED.SINGLE.DIVORCED, 
         ETHNICITY.OTHER.HISPANIC, ETHNICITY.WHITE.BLACK,
         GENDER.M, AGE)
  
add_X <- protect_attributes %>% select(-MARITAL_STATUS.MARRIED, -MARITAL_STATUS.SEPARATED,
         -MARITAL_STATUS.WIDOWED.SINGLE.DIVORCED) %>% as.matrix()

# Supervised Estimator
sup <- Audit_Fairness(Y = dat$y_v[labeled_ind],
                      S = Y_silver_hat[labeled_ind],
                      A = A[labeled_ind],
                      threshold = threshold,
                      method = "supervised")

# Semi-Supervised Estimator using glm(S)
ss <- Audit_Fairness(Y = dat$y_v,
                     S = Y_silver_hat,
                     A = A,
                     threshold = threshold,
                     method = "semi-supervised",
                     X = add_X)
### ----------------------------- Formatting ----------------------------------
sup <- sup$est %>%
  pivot_longer(
    cols = -c(Metric),
    names_to = "Group",
    values_to = "Est"
  ) %>%
  left_join(
    sup$var %>%
      pivot_longer(
        cols = -c(Metric),
        names_to = "Group",
        values_to = "Var"
      ),
    by = c("Metric", "Group")
  ) %>%
  mutate(Method = "Supervised")

ss <- ss$est %>%
  pivot_longer(
    cols = -c(Metric),
    names_to = "Group",
    values_to = "Est"
  ) %>%
  left_join(
    ss$var %>%
      pivot_longer(
        cols = -c(Metric),
        names_to = "Group",
        values_to = "Var"
      ),
    by = c("Metric", "Group")
  ) %>%
  mutate(Method = "SS")

re <- data.frame(
  Metric = sup$Metric, Group = sup$Group,
  RE = sup$Var / ss$Var, Method = "glm(S)"
)

library(ggsci)

rbind(sup, ss) %>%
  filter(!Metric %in% c("TNR", "FNR"))  %>%
  mutate(Method = factor(Method, levels = c("Supervised" ,"SS"))) %>%
  mutate(Group = factor(Group,
    levels = c("Group0", "Group1", "Delta"),
    labels = c("non-Married", "Married", "Delta")
  )) %>%
  ggplot(aes(x = Metric, y = Est, color = Method)) +
  geom_point(position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = Est - 1.96 * sqrt(Var), ymax = Est + 1.9 * sqrt(Var)), position = position_dodge(width = 0.9), width = 0.25) +
  facet_wrap(~Group) +
  theme_bw() +
  theme(
    legend.position = "bottom"
  ) + # Increase facet labels size
  xlab("") +
  ylab("") +
  scale_color_manual(values = pal_nejm()(3)[-1])
ggsave("MIMIC-III/Depression model/Marital_Est.png", width = 12, height = 6)
```

## RE 

```{r, fig.width=8, fig.height=4}
re %>%
  data.frame()  %>%
  filter(!Metric %in% c("TNR", "FNR"))  %>%
  mutate(Group = factor(Group,
    levels = c("Group0", "Group1", "Delta"),
    labels = c("non-Married", "Married", "Delta")
  )) %>%
  ggplot(aes(x = Metric, y = sqrt(RE), fill = Group)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_bw() +
  xlab("") +
  ylab("Confidence Interval Length Ratio\n Supervised : Semi-Supervised") +
  scale_fill_cosmic() + 
  geom_hline(yintercept = 1, linetype = "dashed") +
  theme(
    legend.position = "bottom"
  )

ggsave("MIMIC-III/Depression model/Marital_RE.png", width = 8, height = 4)
```


\clearpage

# Insurance Type (Private vs Public)

```{r}
dat$is_public <- ifelse(dat$INSURANCE %in% c("Government", "Medicaid", "Medicare"), 1, 0)
cat("Public in labeled dataset ", mean(dat$is_public[labeled_ind]), "\n")
cat("Public in unlabeled dataset ", mean(dat$is_public[-labeled_ind]), "\n")

```

## Calibration

```{r, fig.width=6, fig.height=3}
par(mfrow = c(1, 2))
p <- roc(dat$y_v[dat$is_public == 0], Y_silver_hat[dat$is_public == 0], plot = TRUE,  print.auc = TRUE, main = "Private")
p <- roc(dat$y_v[dat$is_public == 1], Y_silver_hat[dat$is_public == 1], plot = TRUE, print.auc = TRUE, main = "Public")
```


```{r, fig.width=6, fig.height=3}
# protected attributes
A <- dat$is_public

# Compute calibration data for overall and each subgroup
calibration_overall <- compute_calibration_data(Y_silver_hat[labeled_ind], dat$y_v[labeled_ind])
calibration_0 <- compute_calibration_data(Y_silver_hat[labeled_ind][A[labeled_ind] == 0], dat$y_v[labeled_ind][A[labeled_ind] == 0])
calibration_1 <- compute_calibration_data(Y_silver_hat[labeled_ind][A[labeled_ind] == 1], dat$y_v[labeled_ind][A[labeled_ind] == 1])

p1 <- ggplot(calibration_0, aes(x = mean_prediction, y = observed_frequency)) +
  geom_point() +
  geom_line() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "black") +
  ggtitle("Female")

p2 <- ggplot(calibration_1, aes(x = mean_prediction, y = observed_frequency)) +
  geom_point() +
  geom_line() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "black") +
  ggtitle("Male")

ggarrange(p1, p2, ncol = 2)
```

## Point Estimate at Overall FPR = 10%

```{r, fig.width=8, fig.height=4}
protect_attributes <- X_structured %>%
  select(INSURANCE.Medicare.Private, INSURANCE.Self.Pay.Government,
         MARITAL_STATUS.MARRIED, MARITAL_STATUS.SEPARATED,
         MARITAL_STATUS.WIDOWED.SINGLE.DIVORCED, 
         ETHNICITY.OTHER.HISPANIC, ETHNICITY.WHITE.BLACK,
         GENDER.M, AGE)
  
add_X <- protect_attributes %>% select(-MARITAL_STATUS.MARRIED, -MARITAL_STATUS.SEPARATED,
         -MARITAL_STATUS.WIDOWED.SINGLE.DIVORCED) %>% as.matrix()

# Supervised Estimator
sup <- Audit_Fairness(Y = dat$y_v[labeled_ind],
                      S = Y_silver_hat[labeled_ind],
                      A = A[labeled_ind],
                      threshold = threshold,
                      method = "supervised")

# Semi-Supervised Estimator using glm(S)
ss <- Audit_Fairness(Y = dat$y_v,
                     S = Y_silver_hat,
                     A = A,
                     threshold = threshold,
                     method = "semi-supervised",
                     X = add_X)
### ----------------------------- Formatting ----------------------------------
sup <- sup$est %>%
  pivot_longer(
    cols = -c(Metric),
    names_to = "Group",
    values_to = "Est"
  ) %>%
  left_join(
    sup$var %>%
      pivot_longer(
        cols = -c(Metric),
        names_to = "Group",
        values_to = "Var"
      ),
    by = c("Metric", "Group")
  ) %>%
  mutate(Method = "Supervised")

ss <- ss$est %>%
  pivot_longer(
    cols = -c(Metric),
    names_to = "Group",
    values_to = "Est"
  ) %>%
  left_join(
    ss$var %>%
      pivot_longer(
        cols = -c(Metric),
        names_to = "Group",
        values_to = "Var"
      ),
    by = c("Metric", "Group")
  ) %>%
  mutate(Method = "Semi-Supervised")

re <- data.frame(
  Metric = sup$Metric, Group = sup$Group,
  RE = sup$Var / ss$Var, Method = "glm(S)"
)

library(ggsci)

rbind(sup, ss) %>%
  filter(!Metric %in% c("TNR", "FNR"))  %>%
  mutate(Method = factor(Method, levels = c("Supervised" ,"Semi-Supervised"))) %>%
  mutate(Group = factor(Group,
    levels = c("Group0", "Group1", "Delta"),
    labels = c("Private", "Public", "Delta")
  )) %>%
  ggplot(aes(x = Metric, y = Est, color = Method)) +
  geom_point(position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = Est - 1.96 * sqrt(Var), ymax = Est + 1.9 * sqrt(Var)), position = position_dodge(width = 0.9), width = 0.25) +
  facet_wrap(~Group) +
  theme_bw() +
  theme(
    legend.position = "bottom"
  ) + # Increase facet labels size
  xlab("") +
  ylab("") +
  scale_color_manual(values = pal_nejm()(3)[-1])
ggsave("MIMIC-III/Depression model/Insurance_Est.png", width = 12, height = 6)
```

## RE 

```{r, fig.width=8, fig.height=4}
re %>%
  data.frame()  %>%
  filter(!Metric %in% c("TNR", "FNR"))  %>%
  mutate(Group = factor(Group,
    levels = c("Group0", "Group1", "Delta"),
    labels = c("Private", "Public", "Delta")
  )) %>%
  ggplot(aes(x = Metric, y = sqrt(RE), fill = Group)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_bw() +
  xlab("") +
  ylab("Confidence Interval Length Ratio\n Supervised : Semi-Supervised") +
  scale_fill_cosmic() + 
  geom_hline(yintercept = 1, linetype = "dashed") +
  theme(
    legend.position = "bottom"
  )

ggsave("MIMIC-III/Depression model/Insurance_RE.png", width = 8, height = 4)
```
